### ISSUE TITLE
General development plan

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/SpySharp#3]
SpySharp should become a modern open-source (and open-licensed) ManagedSpy analogue. To achieve this target, we need to produce some small machinery pieces and finally put them together.
- [ ] #2: Simple hook IPC protocol
- [ ] #4: Deployment of x32 and x64 hooks
- [ ] #6: GUI to interfere with processes
